fastlane_version "2.13.0"

default_platform :android

platform :android do

  desc "Generate develop build"
  lane :develop do |options|
    gradle(task:"clean")
    gradle(task:"assembleRelease")
  end
end
